esphome:
  name: airq32-w2
  friendly_name: AirQ32-W2
  on_boot:
    - delay: 5s

external_components:
  #- source: github://rafaalbelda/cm1106sl_ns@i2c
  - source: github://rafaalbelda/cm1106sl_ns@uart
    components: [cm1106sl_ns]
    refresh: 1h #0s
#     - source:
#       type: git
#       url: https://github.com/rafaalbelda/cm1106sl_ns
#       ref: 44633e2c3778459598545e45e99cbe86a7a98294
#     components: [ cm1106sl_ns ]
#     refresh: 

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: esp-idf

# Enable logging
logger:
#  level: VERBOSE

# Enable Home Assistant API
api:
  encryption:
    key: "Fwy7bN2zDEjkCnrFapHhqnEElSg573EZ0Y8NO549x6A="

  # on_client_connected:
  #   - wait_until:
  #       condition:
  #         api.connected:
  #           state_subscription_only: true
  #   - lvgl.widget.show: lbl_hastatus
  # on_client_disconnected:
  #   - if:
  #       condition:
  #         lambda: 'return (0 == client_info.find("Home Assistant "));'
  #       then:
  #         - lvgl.widget.hide: lbl_hastatus

ota:
  - platform: esphome
    password: "b1aea7cd2f9fe0b199583633ee38d4fd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Airq32-W2 Fallback Hotspot"
    password: "PTi8ZbbmVD57"

captive_portal:

uart:
  - id: uart_pm
    rx_pin: 16
    tx_pin: 17
    baud_rate: 9600
    rx_timeout: 10
  #  debug:
  - id: uart_cm
    rx_pin: 33
    tx_pin: 32
    baud_rate: 9600
  #  debug:

i2c:
  - id: i2c_main
    sda: GPIO21
    scl: GPIO22
    scan: true

spi:
  - id: spi_bus
    clk_pin: 18
    mosi_pin: 23
    #miso_pin: 19

sensor:

  - platform: sgp4x
    voc:
      name: "VOC Index"
    nox:
      name: "NOx Index"

    compensation:
      humidity_source: my_humidity
      temperature_source: my_temperature

  # - platform: cm1106
  #   uart_id: uart_cm
  #   co2:
  #     name: CO2
  - platform: cm1106sl_ns
    id: my_co2
    uart_id: uart_cm
    update_interval: 60s
    config_period: 60
    smoothing_samples: 2
    abc_active: true
    abc_cycle_days: 7
    abc_baseline: 400
    co2:
      name: "CO2 Level"
      id: co2
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_co2
              text:
                format: "%.0f"
                args: [ 'x' ]
                if_nan: "--"

  - platform: bme280_i2c
    i2c_id: i2c_main
    address: 0x76
    temperature:
      name: "Temperatura"
      id: my_temperature
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_temp
              text:
                format: "%.1f°C"
                args: [ 'x' ]
                if_nan: "--"

    pressure:
      name: "Presión"
      id: my_pressure
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pressure
              text:
                format: "%.0f"
                args: [ 'x' ]
                if_nan: "--"

    humidity:
      name: "Humedad"
      id: my_humidity
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_humidity
              text:
                format: "%.1f%"
                args: [ 'x' ]
                if_nan: "--"
    update_interval: 60s  # Synchronized with CO2 sensor 

  - platform: absolute_humidity
    name: Absolute Humidity
    temperature: my_temperature
    humidity: my_humidity

  - platform: pmsx003
    uart_id: uart_pm
    type: PMSX003
    
    # pm_1_0_std:
    #   name: "PM1.0 std"

    # pm_2_5_std:
    #   name: "PM2.5 std"

    # pm_10_0_std:
    #   name: "PM10.0 std"

    pm_1_0:
      name: "PM1.0"
      id: pm1_sensor
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm1
              text:
                format: "%.0f"
                args: [ 'x' ]
                if_nan: "--"

    pm_2_5:
      name: "PM2.5"
      id: pm25_sensor
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm25
              text:
                format: "%.0f"
                args: [ 'x' ]
                if_nan: "--"

    pm_10_0:
      name: "PM10"
      id: pm10_sensor
      on_value:
        then:
          - lvgl.label.update:
              id: lbl_pm10
              text:
                format: "%.0f"
                args: [ 'x' ]
                if_nan: "--"

    update_interval: 60s  # Synchronized with other sensors

  - platform: aqi
    name: "European Air Quality Index"
    pm_2_5: pm25_sensor
    pm_10_0: pm10_sensor
    calculation_type: CAQI
    id: euaqi
    on_value:
      then:
        - lvgl.label.update:
            id: lbl_aqi_1
            text:
              format: "%.0f"
              args: [ 'x' ]
              if_nan: "--"
        - lvgl.label.update:
            id: lbl_aqi_2
            text:
              format: "%.1f"
              args: [ 'x' ]
              if_nan: "--"
        - lvgl.label.update:
            id: lbl_aqi_3
            text:
              format: "%.1f"
              args: [ 'x' ]
              if_nan: "--"

  - platform: homeassistant
    id: ha_weather_temperature
    entity_id: weather.aemet
    attribute: temperature

  - platform: homeassistant
    id: ha_weather_apparent_temperature
    entity_id: sensor.aemet_temperature_feeling

  - platform: homeassistant
    id: ha_weather_temperature_high
    entity_id: sensor.aemet_daily_forecast_temperature

  - platform: homeassistant
    id: ha_weather_temperature_low
    entity_id: sensor.aemet_daily_forecast_temperature_low

  - platform: homeassistant
    id: ha_weather_precipitation_probability
    entity_id: sensor.aemet_daily_forecast_precipitation_probability

  - platform: homeassistant
    id: ha_weather_humidity
    entity_id: weather.aemet
    attribute: humidity

text_sensor:
  - platform: homeassistant
    id: ha_weather_condition
    entity_id: weather.aemet

binary_sensor:
  - platform: gpio
    pin: 
        number: GPIO14
        mode: INPUT_PULLUP
        inverted: true
    name: "Button"
    id: toggle_display
    on_press:
      then:
      - lvgl.page.next


font:
    # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: font10
    size: 10
  - file: "gfonts://Roboto"
    id: font16
    size: 16
  - file: "gfonts://Roboto"
    id: font32
    size: 32
  - file: "gfonts://Roboto"
    id: font48
    size: 48
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
    id: mdi_icons_18
    size: 18
    bpp: 4
    glyphs: [
      "\U000F0D43", # mdi-air-filter
      "\U000F07E4", # mdi-molecule-co2
      "\U000F00B5", # mdi-blur
      "\U000F050F", # mdi-thermometer
      "\U000F058E", # mdi-water-percent
      "\U000F029A", # mdi-gauge
      "\U000F0599", # mdi-weather-sunny
      "\U000F0595", # mdi-weather-partly-cloudy
      "\U000F0590", # mdi-weather-cloudy
      "\U000F0597", # mdi-weather-rainy
      "\U000F0596", # mdi-weather-pouring
      "\U000F0593", # mdi-weather-lightning
      "\U000F0598", # mdi-weather-snowy
      "\U000F0591", # mdi-weather-fog
      "\U000F059D", # mdi-weather-windy
      ]
  - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf"
    id: mdi_weather_48
    size: 48
    bpp: 4
    glyphs: [
      "\U000F0599", # mdi-weather-sunny
      "\U000F0595", # mdi-weather-partly-cloudy
      "\U000F0590", # mdi-weather-cloudy
      "\U000F0597", # mdi-weather-rainy
      "\U000F0596", # mdi-weather-pouring
      "\U000F0593", # mdi-weather-lightning
      "\U000F0598", # mdi-weather-snowy
      "\U000F0591", # mdi-weather-fog
      "\U000F059D", # mdi-weather-windy
      ]

image:
  - file: https://media.esphome.io/logo/logo.png
    id: boot_logo
    resize: 200x200
    type: RGB565
    transparency: alpha_channel


display:
  - platform: ssd1306_i2c
    i2c_id: i2c_main
    model: "SSD1306 128x64"
    id: my_display
    auto_clear_enabled: false
    update_interval: 1s

lvgl:
  displays:
    - my_display
  bg_color: 0x000000
  text_color: 0xFFFFFF
  pad_all: 0
  
  pages:
    - id: screen_aqi_co2
      bg_color: 0x000000
      bg_opa: COVER
      pad_all: 0
      widgets:
        - label:
            text: "AQI"
            align: TOP_LEFT
            x: 3
            y: 2
            text_font: font16
            text_color: 0xFFFFFF
        - label:
            id: lbl_aqi_1
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 0
            width: 128
            text_font: font32
            text_align: CENTER
            text_color: 0xFFFFFF
        - line:
            points: 
              - 0, 32
              - 127, 32
            line_color: 0xFFFFFF
            line_width: 1
        - label:
            text: "CO2"
            align: TOP_LEFT
            x: 3
            y: 35
            text_font: font16
            text_color: 0xFFFFFF
        - label:
            id: lbl_co2
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 32
            width: 128
            text_font: font32
            text_align: CENTER
            text_color: 0xFFFFFF
    
    - id: screen_aqi_pm
      bg_color: 0x000000
      bg_opa: COVER
      pad_all: 0
      widgets:
        - label:
            text: "AQI"
            align: TOP_LEFT
            x: 3
            y: 2
            text_font: font16
            text_color: 0xFFFFFF
        - label:
            id: lbl_aqi_2
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 0
            width: 128
            text_font: font32
            text_align: CENTER
            text_color: 0xFFFFFF
        - line:
            points: 
              - 0, 32
              - 127, 32
            line_color: 0xFFFFFF
            line_width: 1
        - line:
            points:
              - 42, 32
              - 42, 63
            line_color: 0xFFFFFF
            line_width: 1
        - line:
            points:
              - 85, 32
              - 85, 63
            line_color: 0xFFFFFF
            line_width: 1
        - label:
            text: "PM1.0"
            align: TOP_LEFT
            x: 2
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_pm1
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF
        - label:
            text: "PM2.5"
            align: TOP_LEFT
            x: 44
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_pm25
            text: "0"
            align: TOP_LEFT
            x: 43
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF
        - label:
            text: "PM10"
            align: TOP_LEFT
            x: 88
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_pm10
            text: "0"
            align: TOP_LEFT
            x: 86
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF
    
    - id: screen_aqi_climate
      bg_color: 0x000000
      bg_opa: COVER
      pad_all: 0
      widgets:
        - label:
            text: "AQI"
            align: TOP_LEFT
            x: 3
            y: 2
            text_font: font16
            text_color: 0xFFFFFF
        - label:
            id: lbl_aqi_3
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 0
            width: 128
            text_font: font32
            text_align: CENTER
            text_color: 0xFFFFFF
        - line:
            points: 
              - 0, 32
              - 127, 32
            line_color: 0xFFFFFF
            line_width: 1
        - line:
            points:
              - 42, 32
              - 42, 63
            line_color: 0xFFFFFF
            line_width: 1
        - line:
            points:
              - 85, 32
              - 85, 63
            line_color: 0xFFFFFF
            line_width: 1
        - label:
            text: "T"
            align: TOP_LEFT
            x: 3
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_temp
            text: "0"
            align: TOP_LEFT
            x: 0
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF
        - label:
            text: "H"
            align: TOP_LEFT
            x: 45
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_humidity
            text: "0"
            align: TOP_LEFT
            x: 43
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF
        - label:
            text: "P"
            align: TOP_LEFT
            x: 88
            y: 35
            text_font: font10
            text_color: 0xFFFFFF
        - label:
            id: lbl_pressure
            text: "0"
            align: TOP_LEFT
            x: 86
            y: 47
            width: 42
            text_font: font16
            text_align: CENTER
            text_color: 0xFFFFFF

    
